defaults: &defaults
  working_directory: ~/qutebrowser-ci

version: 2
jobs:
  arch:
    <<: *defaults
    docker:
      - image: qutebrowser/travis:archlinux
    environment:
      - DOCKER: "archlinux"
    steps:
      - checkout
      - run: tox -e py36

workflows:
  version: 2
  build_and_test:
    jobs:
      - arch
